language: cpp
compiler: gcc
os: linux
dist: bionic

#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test

before_script:
    - sudo apt-get update
    - sudo apt-get install -y libcppunit-dev
    - mkdir .aux_deps
    - wget https://root.cern/download/root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz
    - tar zxf root_v6.18.02.Linux-ubuntu18-x86_64-gcc7.4.tar.gz -C .aux_deps
    - . ./.aux_deps/root/bin/thisroot.sh
    - mkdir build
    - cd build
    - cmake ..
script:
    - make
    - make test
